export const headquartersLocationOptions = [
  'New York, New York, United States',
  'San Francisco, California, United States',
  'London, England, United Kingdom',
  'Los Angeles, California, United States',
  'Chicago, Illinois, United States',
  'Boston, Massachusetts, United States',
  'Seattle, Washington, United States',
  'Austin, Texas, United States',
  'Paris, Ile-de-France, France',
  'Palo Alto, California, United States',
  'Toronto, Ontario, Canada',
  'San Diego, California, United States',
  'Berlin, Berlin, Germany',
  'Beijing, Beijing, China',
  'Mountain View, California, United States',
  'Singapore, Central Region, Singapore',
  'San Jose, California, United States',
  'Bangalore, Karnataka, India',
  'Mumbai, Maharashtra, India',
  'Cambridge, Massachusetts, United States',
  'Atlanta, Georgia, United States',
  'Washington, District of Columbia, United States',
  'Sunnyvale, California, United States',
  'Tel Aviv, Tel Aviv, Israel',
  'Vancouver, British Columbia, Canada',
  'Tokyo, Tokyo, Japan',
  'Stockholm, Stockholms Lan, Sweden',
  'Dublin, Dublin, Ireland'
];

export const industryOptions = [
  'Other',
  'Software',
  'Health Care',
  'E-Commerce',
  'Mobile',
  'Biotechnology',
  'Information Technology',
  'Manufacturing',
  'Enterprise Software',
  'Apps',
  'Financial Services',
  'Social Media',
  'Advertising',
  'SaaS',
  'Analytics',
  'Real Estate',
  'Hardware',
  'Travel',
  'FinTech',
  'Retail',
  'Automotive',
  'Service Industry',
  'Telecommunications',
  'Music',
  'Marketing',
  'Sports',
  'Video',
  'Therapeutics',
  'Medical Device',
  'Search Engine',
  'Consulting',
  'News',
  'Fashion',
  'Hospitality',
  'Artificial Intelligence'
];
